# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzfNqlFIa6CHXS-7HnWecVHRt7WpHJDv
"""

import pandas as pd
import matplotlib.pyplot as plt


data = pd.read_csv("veteran_employment_outcomes.csv.csv", sep=';')


print(data.head())



data['agegrp'].value_counts().plot(kind='bar', color='purple')
plt.xlabel('Age Group')
plt.ylabel('Count')
plt.title('Distribution of Age Groups among Veterans')
plt.show()